package my.test.mapper;

import java.util.List;

import my.test.pojo.Authority;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated
     */
    Authority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Authority record);

	List<Authority> selectAll();
	List<Authority> selectAuthByPid(Long id);
}